# -*- coding: utf-8 -*-
"""desafio_de_projeto_ETL.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jmgFdl6JXX1_g5ftI755JovucO6Y65W4
"""

import pandas as pd
import requests
import json

df = pd.read_csv('etl.csv')
user_id = df['Id_users'].tolist()

sdw2023_api_url = 'https://sdw-2023-prd.up.railway.app'

def get_user(id):
  response = requests.get(f'{sdw2023_api_url}/users/{id}')
  return response.json() if response.status_code == 200 else None

users = [ user for id in user_id if (user := get_user(id)) is not None]
print(json.dumps(users, indent=2))

!pip install openai

openai_api_key = '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'

from openai.api_resources import completion
import openai

openai.api_key  = openai_api_key

def generate_ai_news(user):

  completion = openai.ChatCompletion.create(
  model="gpt-3.5-turbo",
  messages=[
    {"role": "system", "content": "Você é um especialista em Marketing bancário"},
    {"role": "user", "content": f"Crie uma mensagem para {user['name']} sobre a importância dos investimentos (máximo de 100 caracteres)"}
  ]
  )

  return completion.choices[0].message.content
for user in users:
  news = generate_ai_news(user)
  print(news)
  user['news'].append({
      "icon": 'https://digitalinnovationone.github.io/santander-dev-week-api/icons/credit.svg',
      "description": news
  })

def update_user(user):
  response = requests.put(f"{sdw2023_api_url}/users/{user['id']}", json=user)
  return True if response.status_code == 200 else False
for user in users:
  sucess = update_user(user)
  print(f"User{user['name']} updated ? {sucess}")